# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RibsTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RibsTutorial
  pod 'RIBs', :git => 'https://github.com/uber/RIBs', :commit => 
'ffc489f00db785c8c0051678393f7aba0d52f1a4'
  pod 'SnapKit', '~> 5.0.0'


  target 'RibsTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RibsTutorialUITests' do
    # Pods for testing
  end

end
