# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RibsTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RibsTutorial

  
  target 'RibsTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RibsTutorialUITests' do
    # Pods for testing
  end

end
